- mlflow_project/MLproject
- mlflow_project/README-Databricks.md
- mlflow_project/README.md
- mlflow_project/src/rf_test/train.py
- mlflow_project/src/rf_test/train_simple.py
This change adds a non-hyperopt simplified MLFlow example and makes a few other tweaks to the READMEs.﻿
> [REVIEW] MLFlow updates for blog post

- README.md
Adding Databricks to the Readme
> UPDATE readme with databricks

- azure/code/train_rapids.py
- azure/notebooks/HPO-RAPIDS.ipynb
- Updated RAPIDS container to 0.16 stable
- Added CV-folds and multi-GPU to argparse
- Added MLflow logging
> [REVIEW] Update container and notebook, add mlflow

- .github/workflows/docker-description.yaml
This PR ensures that the DockerHub description gets updated when the GitHub Action itself is modified (in addition to the README.md).
> Update GitHub Action for DockerHub Description

- common/docker/Dockerfile.training.unified
Modified unified Dockerfile to use RAPIDS core images
> Update Docker repo

- gcp/README.md
- gcp/docker/Dockerfile.jupyter_notebook
> Docs fixes

- azure/README.md
- azure/notebooks/HPO-RAPIDS.ipynb
- azure/notebooks/Train-RAPIDS.ipynb
See https://github.com/rapidsai/cloud-ml-examples/issues/58 
Replace conda environment setup with CloudML docker container.
> [REVIEW] Update Azure Notebook to use CloudML container

- azure/README.md
- azure/notebooks/HPO-RAPIDS.ipynb
- azure/notebooks/Train-RAPIDS.ipynb
- azure/notebooks/azure_mnmg.ipynb
Updating REAMDE and notebooks to stable containers
> [REVIEW] Update to Azure examples 0.18 containers

- azure/notebooks/HPO-RAPIDS.ipynb
Migrating Estimator to ScriptRunConfig
> [REVIEW] Update Azure HPO notebook

- aws/autogluon/Dockerfile
- aws/autogluon/autogluon_airline.ipynb
- aws/autogluon/lifecycle_script
- aws/rapids_sagemaker_hpo.ipynb
- Also commented out the packages in the Dockerfile which are pre-installed by the unified container
Note that we should probably update the /notebook_setup directory as that is still pointing to 0.15 instructions
> AutoGluon example; Unified container with latest tag

- common/docker/Dockerfile.training.unified
Adding:
- aws/code/workflows/MLWorkflowMultiCPU.py 
- aws/code/workflows/MLWorkflowMultiGPU.py
- aws/code/workflows/MLWorkflowSingleCPU.py
- aws/code/workflows/MLWorkflowSingleGPU.py
> Adding AWS workflows to unified container

- common/code/create_packed_conda_env
- gcp/README.md
- gcp/notebook_setup/README.md
- mlflow/docker_environment/Dockerfile.training
Updated a few out of date documents and versions.
> Update language referencing old rapids release numbers

- azure/README.md
- azure/notebooks/Dockerfile
- azure/notebooks/HPO-RAPIDS.ipynb
- azure/notebooks/HPO-SKLearn.ipynb
- azure/notebooks/Train-RAPIDS.ipynb
- azure/notebooks/Train-SKLearn.ipynb
- azure/notebooks/azure_mnmg.ipynb
Update all references to 0.19 for Azure examples
> [REVIEW] Update Azure examples references to 0.19

- aws/notebook_setup/README.md
- azure/notebook_setup/README.md
- common/code/create_packed_conda_env
- gcp/notebook_setup/README.md
Remove `defaults` channel from conda build
> ENH Remove defaults channel from conda build

- databricks/src/rapids_install_cuml0.13_cuda10.0_ubuntu16.04.sh
- mlflow/docker_environment/envs/conda.yaml
- mlflow/local_environment/envs/conda.yaml
- optuna/notebooks/jupytercon_demo/conda/conda.yaml
Remove conda defaults channel in dev environments
> ENH Remove conda defaults channel in dev environments

- common/docker/DockerHubREADME.md
> Fix DockerHubREADME.md typo

- dask/kubernetes/specs/sched-spec.yaml
- dask/kubernetes/specs/worker-spec-custom.yaml
- dask/kubernetes/specs/worker-spec.yaml
Reverting to values that don't break initial workflow
> [REVIEW] Update YAML valus for Dask Kubernetes example

- azure/README.md
- azure/notebooks/remote-explanation/azure-gpu-shap.ipynb
- azure/notebooks/remote-explanation/train_explain.py
- Closes https://github.com/rapidsai/cloud-ml-examples/issues/114 
- Adds a simple classification example with Higgs dataset for explainability on Azure
- Using `N_ROWS` as the dataset is huge and causes memory error for larger values
- Right now, we need to specify `interpret-community==0.18` because `azureml-interpret` uses 0.17; but going forward we can get rid of it as it'll get updated in the next release
> [REVIEW] Add GPU SHAP on Azure

- databricks/README.md
I have a minor change in the readme file in the docker command.
> minor change in readme

- aws/environment_setup/lifecycle_script
Update autogluon lifecycle script. Verified version on sagemaker.
> [REVIEW] Update lifecycle configuration to 21.06

- azure/kubernetes/Dask_cuML_Exploration_Full.ipynb
- azure/kubernetes/Detailed_setup_guide.md
- azure/kubernetes/Dockerfile
- azure/kubernetes/MNMG_XGBoost.ipynb
- azure/kubernetes/podspecs/azure/cpu-worker-specs.yml
- azure/kubernetes/podspecs/azure/cuda-worker-specs.yml
- azure/kubernetes/podspecs/azure/scheduler-specs.yml
This PR addresses #126 . Very minor changes.
> Added changes for RAPIDS 21.06 in Azure K8s notebooks

- azure/notebooks/remote-explanation/azure-gpu-shap.ipynb
- azure/notebooks/remote-explanation/train_explain.py
See https://github.com/rapidsai/cloud-ml-examples/issues/126
> [REVIEW ] Update SHAP example to 21.06 

- dask/notebooks/HPO_demo.ipynb
- gcp/notebooks/custom_hpo.ipynb
- mlflow/docker_environment/src/rf_test/train.py
- mlflow/local_environment/src/rf_test/train.py
- mlflow/local_environment/src/rf_test/train_simple.py
- optuna/notebooks/azure-optuna/project_folder/train_optuna.py
- optuna/notebooks/jupytercon_demo/RAPIDS_xfeat_Optuna-GPU.ipynb
- optuna/notebooks/optuna_rapids.ipynb
- ray/notebooks/Ray_RAPIDS_HPO.ipynb
starting to locate and update hardcoded RAPIDS versions and outdated usages (i.e., `train_test_split`)
- not including any databricks files
> [IN PROGRESS] Update cuML API

- aws/code/Dockerfile
- aws/environment_setup/README.md
- dask/README.md
- dask/kubernetes/Dockerfile
- dask/kubernetes/specs/sched-spec-custom.yaml
- dask/kubernetes/specs/sched-spec.yaml
- dask/kubernetes/specs/worker-spec-custom.yaml
- dask/kubernetes/specs/worker-spec.yaml
- optuna/notebooks/azure-optuna/run_optuna.ipynb
- ray/README.md
list of all files with RAPIDS version hardcoded somewhere (e.g. '21.06', 'rapidsai:0.15', etc.): 
[hardcoded_rapids.txt](https://github.com/rapidsai/cloud-ml-examples/files/6734704/hardcoded_rapids.txt)
> [REVIEW] Update RAPIDS versions

- aws/README.md
- aws/rapids_ec2_mnmg.ipynb
Adding Dask-cloudprovider example to run MNMG on AWS EC2
> [REVIEW] Add AWS MNMG example

- common/docker/DockerHubREADME.md
Update readme to latest version numbers.  Will update following pages:
https://hub.docker.com/r/rapidsai/rapidsai/
https://hub.docker.com/r/rapidsai/rapidsai-cloud-ml
https://catalog.ngc.nvidia.com/orgs/nvidia/teams/rapidsai/containers/rapidsai-cloud-ml
> bump version numbers

- databricks/src/rapids_install_cuml0.13_cuda10.0_ubuntu16.04.sh
- mlflow/docker_environment/envs/conda.yaml
> Specifying ucx-proc in environments.

- dask/notebooks/HPO_demo.ipynb
Closes https://github.com/rapidsai/cloud-ml-examples/issues/186
* Use a new link for the airline dataset
* Add option to use a smaller fraction of the airline dataset, as the full dataset is large
* Replace `to_array()` to `to_numpy()`
> Update Dask HPO notebook

- README.md
- Added checks/Xs to the notebook links denoting if they work or not in 22.08
- Added a header to denote what the checks/Xs mean
> Updating readme to include notebook status

- README.md
- ci/axis.yaml
- common/code/create_packed_conda_env
- common/docker/DockerHubREADME.md
- common/docker/Dockerfile.training.unified
This PR is for updating the Cloud ML container and tooling to RAPIDS 22.10
closes #170
> 22.10 Container Updates
